"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.index import get_image
from insta485.views.comments import comment_actions
from insta485.views.likes import likes
from insta485.views.users import show_user
from insta485.views.followers import show_followers
from insta485.views.following import show_following
from insta485.views.follow import follow
from insta485.views.posts import posts
from insta485.views.explore import explore
from insta485.views.login import show_login
from insta485.views.logout import show_logout
from insta485.views.create import create_user
from insta485.views.delete import delete_account
from insta485.views.edit import edit_info
from insta485.views.password import update_password
from insta485.views.accounts import account_crud
from insta485.views.auth import status
